### ISSUE TITLE
Qfaas-api-core deployment : env-secret

### ISSUE THREAD

**Issue by mopoa** [Cloudslab/qfaas#1]
Hi,
while deploying the api-core based on the "Quantum Serverless Paradigm and Application Development using the QFaaS Framework"  i encountered an error which looks like it's a problem with the env-secret.
Is it possible to use github instead of gitlab?
I'm giving a huge possibility that my .env file has a problem.
![Screenshot from 2024-08-20 01-50-38](https://github.com/user-attachments/assets/af1b7634-5dfa-43c0-8f67-49d947fcd13f)

I'll be grateful if you help me through this problem.
![Screenshot from 2024-08-20 01-48-56](https://github.com/user-attachments/assets/71a468c3-b68a-46a7-a3a5-3e3840bc7212)

the secret is been created and existing under the qfaas namespace

**Comment by hoaiocom** [comment]
Hi @mopoa,
Could you provide more information about your K8s setup? Please note that this will work with K8s 1.6+ (https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables).
Currently, QFaaS is compatible with Gitlab only, and I'm still working on migrating QFaaS to be independent of Gitlab but it will take a bit more time.

**Comment by mopoa** [comment]
Thanks alot for your response.
I'm using microk8s as like the documentation recommended.
![Screenshot from 2024-08-20 16-42-46](https://github.com/user-attachments/assets/93b19f81-084a-470e-818e-d66c3d421a95)

by the way i havn't installed gitlab at the moment

**Comment by hoaiocom** [comment]
No worries, you may try out the sample example of using secrets: https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables
and double-check the deployment.yaml file again
